
## -- Read data into data frame -- ##
data <- read.csv("./repdata_data_StormData.csv.bz2", header = TRUE, sep=",")

## --  Simplify data set to include only columns we need to look at -- ##
## --  , summing two columns and creating a new column, lastly we   -- ##
## -- rename new column generated by agg function                   -- ##
dataAgg2 <- aggregate(data$FATALITIES+data$INJURIES, by=list(Event=data$EVTYPE),FUN=sum)
colnames(dataAgg2)[2] <- "TotHarm"

## -- Reordering column (desc) by total harm -- ##
dataAggOrder2 <- dataAgg2[order(-dataAgg2$TotHarm),]

## -- Grag only the top 5 events -- ##
dataAggOrderSort2 <- head(dataAggOrder2,5)

## -- To make the bar plot more readable, dividing the Total Damage -- ##
## -- value by 100                                                  -- ##
dataAggOrderSort2$TotHarm <- as.numeric(dataAggOrderSort2$TotHarm)
dataAggOrderSort2$TotHarm <- dataAggOrderSort2$TotHarm / 100

## -- Using barplot to represent the top 5 most harmful weather events -- ##
barplot(dataAggOrderSort2$TotHarm,names.arg=dataAggOrderSort2$Event, ylab="Injury + Fatality (x 100)", las=2, col=rainbow(20), ylim=c(0,1000),main="Top 5 Weather Events by Harm"))



## --  Simplify data set to include only columns we need to look at -- ##
## --  , summing two columns and creating a new column, lastly we   -- ##
## -- rename new column generated by agg function                   -- ##
dataAgg1 <- aggregate(data$PROPDMG+data$CROPDMG, by=list(Event=data$EVTYPE),FUN=sum)
colnames(dataAgg1)[2] <- "TotDamage"

## -- Reordering column (desc) by total damage -- ##
dataAggOrder1 <- dataAgg1[order(-dataAgg1$TotDamage),]

## -- Grag only the top 5 events -- ##
dataAggOrderSort1 <- head(dataAggOrder1,5)

## -- To make the bar plot more readable, dividing the Total Damage -- ##
## -- value by 100                                                  -- ##
dataAggOrderSort1$TotDamage <- as.numeric(dataAggOrderSort1$TotDamage)
dataAggOrderSort1$TotDamage <- dataAggOrderSort1$TotDamage / 100

## -- Using barplot to represent the top 5 most damaging weather events -- ##
barplot(dataAggOrderSort1$TotDamage,names.arg=dataAggOrderSort1$Event, ylab="Property + Crop Cost (x100)", las=2,col=rainbow(20),ylim=c(0,400),main="Top 5 Weather Events by Damage"))
